// cocoon-webhook — Admission webhook for stateful VM scheduling and protection.
//
// Mutating (/mutate — Pod CREATE):
//  1. Derives a stable VM name from the Deployment/ReplicaSet owner + replica slot
//  2. Looks up the ConfigMap "cocoon-vm-affinity" for last-known node
//  3. Sets pod.spec.nodeName + cocoon.cis/vm-name annotation
//
// Validating (/validate — Deployment/StatefulSet UPDATE):
//  4. Blocks scale-down for cocoon-type workloads (only scale-up allowed)
//     Agents are stateful VMs — reducing replicas would destroy state.
//     Use the Hibernation CRD to suspend individual agents instead.
//
// For pods without a Deployment owner (bare pods, StatefulSets), the
// webhook uses the pod name directly as the VM name.
package main

import (
	"context"
	"crypto/tls"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/signal"
	"sort"
	"strings"
	"syscall"

	admissionv1 "k8s.io/api/admission/v1"
	appsv1 "k8s.io/api/apps/v1"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/rest"
	"k8s.io/client-go/tools/clientcmd"
	"k8s.io/klog/v2"
)

const (
	affinityConfigMap = "cocoon-vm-affinity"
	vmNameAnnotation  = "cocoon.cis/vm-name"
	cocoonToleration  = "virtual-kubelet.io/provider"
)

var clientset *kubernetes.Clientset

func main() {
	// Use KUBECONFIG if set, otherwise in-cluster
	kubeconfig := os.Getenv("KUBECONFIG")
	var config *rest.Config
	var cfgErr error
	if kubeconfig != "" {
		config, cfgErr = clientcmd.BuildConfigFromFlags("", kubeconfig)
	} else {
		config, cfgErr = rest.InClusterConfig()
	}
	if cfgErr != nil {
		klog.Fatalf("k8s config: %v", cfgErr)
	}
	var csErr error
	clientset, csErr = kubernetes.NewForConfig(config)
	if csErr != nil {
		klog.Fatalf("clientset: %v", csErr)
	}

	// TLS cert (generated by cert-manager or self-signed)
	certFile := os.Getenv("TLS_CERT")
	keyFile := os.Getenv("TLS_KEY")
	if certFile == "" {
		certFile = "/etc/webhook/certs/tls.crt"
	}
	if keyFile == "" {
		keyFile = "/etc/webhook/certs/tls.key"
	}

	mux := http.NewServeMux()
	mux.HandleFunc("/mutate", handleMutate)
	mux.HandleFunc("/validate", handleValidate)
	mux.HandleFunc("/healthz", func(w http.ResponseWriter, r *http.Request) {
		w.WriteHeader(200)
		w.Write([]byte("ok"))
	})

	cert, err := tls.LoadX509KeyPair(certFile, keyFile)
	if err != nil {
		klog.Fatalf("load TLS: %v", err)
	}
	server := &http.Server{
		Addr:    ":8443",
		Handler: mux,
		TLSConfig: &tls.Config{
			Certificates: []tls.Certificate{cert},
		},
	}

	ctx, cancel := signal.NotifyContext(context.Background(), syscall.SIGINT, syscall.SIGTERM)
	defer cancel()

	go func() {
		klog.Info("cocoon-webhook listening on :8443")
		if err := server.ListenAndServeTLS("", ""); err != nil && err != http.ErrServerClosed {
			klog.Fatalf("server: %v", err)
		}
	}()
	<-ctx.Done()
	server.Shutdown(context.Background())
}

func handleMutate(w http.ResponseWriter, r *http.Request) {
	body, err := io.ReadAll(r.Body)
	if err != nil {
		http.Error(w, "read body", 400)
		return
	}

	var review admissionv1.AdmissionReview
	if err := json.Unmarshal(body, &review); err != nil {
		http.Error(w, "decode", 400)
		return
	}

	resp := mutate(review.Request)
	review.Response = resp
	review.Response.UID = review.Request.UID

	out, _ := json.Marshal(review)
	w.Header().Set("Content-Type", "application/json")
	w.Write(out)
}

func mutate(req *admissionv1.AdmissionRequest) *admissionv1.AdmissionResponse {
	if req.Kind.Kind != "Pod" {
		return &admissionv1.AdmissionResponse{Allowed: true}
	}

	var pod corev1.Pod
	if err := json.Unmarshal(req.Object.Raw, &pod); err != nil {
		return &admissionv1.AdmissionResponse{Allowed: true}
	}

	// Only mutate pods with cocoon toleration (VM workloads)
	if !hasCocoonToleration(&pod) {
		return &admissionv1.AdmissionResponse{Allowed: true}
	}

	// Skip mutation for CocoonSet-owned pods — controller handles everything
	for _, ref := range pod.OwnerReferences {
		if ref.Kind == "CocoonSet" {
			klog.Infof("mutate %s/%s: owned by CocoonSet %s, skipping", req.Namespace, req.Name, ref.Name)
			return &admissionv1.AdmissionResponse{
				Allowed: true,
				UID:     req.UID,
			}
		}
	}

	// Already has nodeName set — don't override
	if pod.Spec.NodeName != "" {
		return &admissionv1.AdmissionResponse{Allowed: true}
	}

	// Already has vm-name annotation — don't override
	if pod.Annotations != nil && pod.Annotations[vmNameAnnotation] != "" {
		// But still need to set nodeName from affinity map
		vmName := pod.Annotations[vmNameAnnotation]
		nodeName := lookupVMNode(req.Namespace, vmName)
		if nodeName != "" {
			return patchNodeName(nodeName)
		}
		// No affinity record — let scheduler pick any cocoon node
		return pickCocoonNode()
	}

	// Derive stable VM name from owner (Deployment/RS) + namespace
	vmName := deriveVMName(&pod, req.Namespace, req.Name)

	// Look up last-known node for this VM
	nodeName := lookupVMNode(req.Namespace, vmName)

	patches := []map[string]interface{}{}

	// Ensure annotations map exists
	if pod.Annotations == nil {
		patches = append(patches, map[string]interface{}{
			"op":    "add",
			"path":  "/metadata/annotations",
			"value": map[string]string{},
		})
	}

	// Set vm-name annotation
	patches = append(patches, map[string]interface{}{
		"op":    "add",
		"path":  "/metadata/annotations/" + escapeJSONPointer(vmNameAnnotation),
		"value": vmName,
	})

	// Set nodeName if we have affinity, otherwise let scheduler pick a cocoon node
	if nodeName != "" {
		patches = append(patches, map[string]interface{}{
			"op":    "add",
			"path":  "/spec/nodeName",
			"value": nodeName,
		})
		klog.Infof("mutate %s/%s: vm=%s → node=%s (affinity)", req.Namespace, req.Name, vmName, nodeName)
	} else {
		// First-time: pick any cocoon-pool node
		if node := pickAnyCocoonNode(); node != "" {
			patches = append(patches, map[string]interface{}{
				"op":    "add",
				"path":  "/spec/nodeName",
				"value": node,
			})
			klog.Infof("mutate %s/%s: vm=%s → node=%s (new, round-robin)", req.Namespace, req.Name, vmName, node)
		}
	}

	patchBytes, _ := json.Marshal(patches)
	pt := admissionv1.PatchTypeJSONPatch
	return &admissionv1.AdmissionResponse{
		Allowed:   true,
		Patch:     patchBytes,
		PatchType: &pt,
	}
}

// deriveVMName creates a stable VM name from the pod's owner chain.
// For Deployment pods: vk-{ns}-{deployment-name}-{slot}
// For bare pods: vk-{ns}-{pod-name}
func deriveVMName(pod *corev1.Pod, ns, podName string) string {
	// Walk owner references: Pod → ReplicaSet → Deployment
	deployName := ""
	for _, ref := range pod.OwnerReferences {
		if ref.Kind == "ReplicaSet" {
			// RS name = {deployment}-{hash}, strip the hash
			parts := strings.Split(ref.Name, "-")
			if len(parts) >= 2 {
				deployName = strings.Join(parts[:len(parts)-1], "-")
			}
		}
	}

	if deployName != "" {
		// For Deployment: allocate a replica slot from affinity ConfigMap
		slot := allocateSlot(ns, deployName, podName)
		return fmt.Sprintf("vk-%s-%s-%d", ns, deployName, slot)
	}

	// Bare pod or StatefulSet: use pod name directly
	return fmt.Sprintf("vk-%s-%s", ns, podName)
}

// allocateSlot assigns a stable replica index for a Deployment pod.
// Reads/writes the affinity ConfigMap to track slot assignments.
func allocateSlot(ns, deployName, podName string) int {
	ctx := context.Background()
	cmName := affinityConfigMap

	cm, err := clientset.CoreV1().ConfigMaps(ns).Get(ctx, cmName, metav1.GetOptions{})
	if err != nil {
		// ConfigMap doesn't exist yet — slot 0
		return 0
	}

	// Find existing slot for this pod or an empty slot
	prefix := fmt.Sprintf("vk-%s-%s-", ns, deployName)
	usedSlots := map[int]string{}     // slot → podName
	maxSlot := -1

	for key, val := range cm.Data {
		if strings.HasPrefix(key, prefix) {
			// key = "vk-ns-deploy-0", val = "node:cocoon-pool,pod:xxx"
			slotStr := strings.TrimPrefix(key, prefix)
			slot := 0
			fmt.Sscanf(slotStr, "%d", &slot)
			// Extract pod name from value
			for _, part := range strings.Split(val, ",") {
				if strings.HasPrefix(part, "pod:") {
					usedSlots[slot] = strings.TrimPrefix(part, "pod:")
				}
			}
			if slot > maxSlot {
				maxSlot = slot
			}
		}
	}

	// Check if this pod already has a slot
	for slot, pn := range usedSlots {
		if pn == podName {
			return slot
		}
	}

	// Find first empty slot (pod was deleted)
	for i := 0; i <= maxSlot; i++ {
		if _, used := usedSlots[i]; !used {
			return i
		}
	}

	// All slots occupied — allocate new
	return maxSlot + 1
}

func lookupVMNode(ns, vmName string) string {
	ctx := context.Background()
	cm, err := clientset.CoreV1().ConfigMaps(ns).Get(ctx, affinityConfigMap, metav1.GetOptions{})
	if err != nil {
		return ""
	}
	val, ok := cm.Data[vmName]
	if !ok {
		return ""
	}
	// Format: "node:cocoon-pool,pod:xxx"
	for _, part := range strings.Split(val, ",") {
		if strings.HasPrefix(part, "node:") {
			return strings.TrimPrefix(part, "node:")
		}
	}
	return ""
}

func pickAnyCocoonNode() string {
	ctx := context.Background()
	nodes, err := clientset.CoreV1().Nodes().List(ctx, metav1.ListOptions{
		LabelSelector: "type=virtual-kubelet",
	})
	if err != nil || len(nodes.Items) == 0 {
		// Fallback: list all nodes and find cocoon ones
		nodes, err = clientset.CoreV1().Nodes().List(ctx, metav1.ListOptions{})
		if err != nil {
			return ""
		}
	}

	cocoonNodes := []string{}
	for _, n := range nodes.Items {
		// Match by label type=virtual-kubelet or by taint
		if n.Labels["type"] == "virtual-kubelet" {
			cocoonNodes = append(cocoonNodes, n.Name)
			continue
		}
		for _, taint := range n.Spec.Taints {
			if taint.Key == cocoonToleration {
				cocoonNodes = append(cocoonNodes, n.Name)
				break
			}
		}
	}
	if len(cocoonNodes) == 0 {
		return ""
	}
	sort.Strings(cocoonNodes)
	// Simple round-robin based on time
	return cocoonNodes[int(metav1.Now().UnixNano())%len(cocoonNodes)]
}

func patchNodeName(nodeName string) *admissionv1.AdmissionResponse {
	patches := []map[string]interface{}{{
		"op":    "add",
		"path":  "/spec/nodeName",
		"value": nodeName,
	}}
	patchBytes, _ := json.Marshal(patches)
	pt := admissionv1.PatchTypeJSONPatch
	return &admissionv1.AdmissionResponse{
		Allowed:   true,
		Patch:     patchBytes,
		PatchType: &pt,
	}
}

func pickCocoonNode() *admissionv1.AdmissionResponse {
	node := pickAnyCocoonNode()
	if node == "" {
		return &admissionv1.AdmissionResponse{Allowed: true}
	}
	return patchNodeName(node)
}

func hasCocoonToleration(pod *corev1.Pod) bool {
	for _, t := range pod.Spec.Tolerations {
		if t.Key == cocoonToleration {
			return true
		}
	}
	return false
}

func escapeJSONPointer(s string) string {
	s = strings.ReplaceAll(s, "~", "~0")
	s = strings.ReplaceAll(s, "/", "~1")
	return s
}

// ---------- Validating Webhook: Block Scale-Down ----------

func handleValidate(w http.ResponseWriter, r *http.Request) {
	body, err := io.ReadAll(r.Body)
	if err != nil {
		http.Error(w, "read body", 400)
		return
	}

	var review admissionv1.AdmissionReview
	if err := json.Unmarshal(body, &review); err != nil {
		http.Error(w, "decode", 400)
		return
	}

	resp := validate(review.Request)
	review.Response = resp
	review.Response.UID = review.Request.UID

	out, _ := json.Marshal(review)
	w.Header().Set("Content-Type", "application/json")
	w.Write(out)
}

// validate rejects scale-down (replicas decrease) for cocoon-type Deployments
// and StatefulSets. Agents are stateful VMs — scale-down would destroy state.
// Use the Hibernation CRD to suspend individual agents instead.
func validate(req *admissionv1.AdmissionRequest) *admissionv1.AdmissionResponse {
	allow := &admissionv1.AdmissionResponse{Allowed: true}

	if req.Operation != admissionv1.Update {
		return allow
	}

	switch req.Kind.Kind {
	case "Deployment":
		return validateDeploymentScale(req)
	case "StatefulSet":
		return validateStatefulSetScale(req)
	default:
		return allow
	}
}

func validateDeploymentScale(req *admissionv1.AdmissionRequest) *admissionv1.AdmissionResponse {
	var oldDeploy, newDeploy appsv1.Deployment
	if err := json.Unmarshal(req.OldObject.Raw, &oldDeploy); err != nil {
		return &admissionv1.AdmissionResponse{Allowed: true}
	}
	if err := json.Unmarshal(req.Object.Raw, &newDeploy); err != nil {
		return &admissionv1.AdmissionResponse{Allowed: true}
	}

	// Only guard cocoon-type workloads.
	if !templateHasCocoonToleration(&newDeploy.Spec.Template.Spec) {
		return &admissionv1.AdmissionResponse{Allowed: true}
	}

	oldReplicas := int32(1)
	newReplicas := int32(1)
	if oldDeploy.Spec.Replicas != nil {
		oldReplicas = *oldDeploy.Spec.Replicas
	}
	if newDeploy.Spec.Replicas != nil {
		newReplicas = *newDeploy.Spec.Replicas
	}

	if newReplicas < oldReplicas {
		msg := fmt.Sprintf(
			"cocoon-webhook: scale-down blocked for cocoon Deployment %s/%s (%d → %d). "+
				"Agents are stateful VMs — use Hibernation CRD to suspend individual agents.",
			req.Namespace, req.Name, oldReplicas, newReplicas)
		klog.Infof("validate DENY: %s", msg)
		return &admissionv1.AdmissionResponse{
			Allowed: false,
			Result:  &metav1.Status{Message: msg, Reason: metav1.StatusReasonForbidden},
		}
	}

	return &admissionv1.AdmissionResponse{Allowed: true}
}

func validateStatefulSetScale(req *admissionv1.AdmissionRequest) *admissionv1.AdmissionResponse {
	var oldSTS, newSTS appsv1.StatefulSet
	if err := json.Unmarshal(req.OldObject.Raw, &oldSTS); err != nil {
		return &admissionv1.AdmissionResponse{Allowed: true}
	}
	if err := json.Unmarshal(req.Object.Raw, &newSTS); err != nil {
		return &admissionv1.AdmissionResponse{Allowed: true}
	}

	if !templateHasCocoonToleration(&newSTS.Spec.Template.Spec) {
		return &admissionv1.AdmissionResponse{Allowed: true}
	}

	oldReplicas := int32(1)
	newReplicas := int32(1)
	if oldSTS.Spec.Replicas != nil {
		oldReplicas = *oldSTS.Spec.Replicas
	}
	if newSTS.Spec.Replicas != nil {
		newReplicas = *newSTS.Spec.Replicas
	}

	if newReplicas < oldReplicas {
		msg := fmt.Sprintf(
			"cocoon-webhook: scale-down blocked for cocoon StatefulSet %s/%s (%d → %d). "+
				"Use Hibernation CRD to suspend individual agents.",
			req.Namespace, req.Name, oldReplicas, newReplicas)
		klog.Infof("validate DENY: %s", msg)
		return &admissionv1.AdmissionResponse{
			Allowed: false,
			Result:  &metav1.Status{Message: msg, Reason: metav1.StatusReasonForbidden},
		}
	}

	return &admissionv1.AdmissionResponse{Allowed: true}
}

func templateHasCocoonToleration(spec *corev1.PodSpec) bool {
	for _, t := range spec.Tolerations {
		if t.Key == cocoonToleration {
			return true
		}
	}
	return false
}
