apiVersion: v1
kind: Service
metadata:
  name: cocoon-webhook
  namespace: cocoon-system
  labels:
    app.kubernetes.io/name: cocoon-webhook
spec:
  selector:
    app.kubernetes.io/name: cocoon-webhook
  ports:
    - name: webhook
      port: 443
      targetPort: webhook
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
